name: My First Workflow
on:
  push: 
jobs:
  echo_the_date:
    runs-on: ubuntu-latest
    steps: 
    - name: echo the date
      run: echo "The current time and date is $(date)"
    - name: echo the current branch
      run: echo ${{github.ref_name}}

  test_and_deploy:
    runs-on: ubuntu-latest
    # add api key in github, see below steps @mvn clean test
    env:
      OPENWEATHERMAP_API_KEY: ${{secrets.OPENWEATHERMAP_API_KEY}}
    steps:
    # https://github.com/marketplace/actions/setup-java-jdk
    - name: Setup DJK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'

    # https://github.com/marketplace/actions/setup-maven    
    - name: Setup Maven
      uses: stCarolas/setup-maven@v4.3
      with: 
        maven-version: 3.8.2

    # https://github.com/marketplace/actions/checkout
    - name: checkout the source
      uses: actions/checkout@v3

    - name: Run test
      run: mvn clean test
      # cannot run cos we did not set the API key
      # add in github, setting, secret, action, add secret, copy the key
      